volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: annabera/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/foodgram_static
  frontend:
    image: annabera/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: annabera/foodgram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8500:80