# Generated by Django 3.2.3 on 2024-07-24 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Не более 150 символов. Только буквы, цифры и @/./+/-/_.', max_length=150, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Не более 150 символов. Только буквы, цифры и @/./+/-/_.', max_length=150, unique=True, verbose_name='Фамилия'),
        ),
    ]
