# Generated by Django 3.2.3 on 2024-07-21 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(through='api.ListIngredients', to='api.Ingredients', verbose_name='Список ингридиентов'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(to='api.Tags', verbose_name='Список тегов'),
        ),
        migrations.AddField(
            model_name='listingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='api.ingredients', verbose_name='Ингредиент'),
        ),
        migrations.AddField(
            model_name='listingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='api.recipes', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='listfavorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_favorite', to='api.recipes', verbose_name='Рецепт в избранном'),
        ),
        migrations.AddField(
            model_name='listfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='measurement_unit',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='api.units', verbose_name='Еденица измерения'),
        ),
        migrations.AddField(
            model_name='downloadlistingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_download', to='api.recipes', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='downloadlistingredients',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
