# Generated by Django 3.2.3 on 2024-07-22 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadlistingredients',
            options={'verbose_name': 'Добавлен в список покупок', 'verbose_name_plural': 'Добавленые в списки покупок'},
        ),
        migrations.AlterModelOptions(
            name='units',
            options={'verbose_name': 'Еденица измерения', 'verbose_name_plural': 'Еденицы измерения'},
        ),
        migrations.AlterField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(through='api.ListIngredients', to='api.Ingredients', verbose_name='Список ингредиентов'),
        ),
        migrations.AlterField(
            model_name='units',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название еденицы измерения'),
        ),
    ]
