# Generated by Django 3.2.3 on 2024-07-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240722_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='slug',
            field=models.SlugField(auto_created=True, max_length=32, unique=True, verbose_name='Уникальный идентификатор рецепта'),
        ),
    ]
