# Generated by Django 3.2.3 on 2024-07-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_recipes_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='slug',
        ),
    ]
