# Generated by Django 3.2.3 on 2024-07-28 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20240729_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='measurement_unit',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, related_name='unitingredient', to='api.units', verbose_name='Еденица измерения'),
        ),
    ]
