# Generated by Django 3.2.3 on 2024-07-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_downloadlistingredients_shoppingcartingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(related_name='tagspecipes', to='api.Tags', verbose_name='Список тегов'),
        ),
    ]
